language: java
addons:
  sonarcloud:
    organization: johnymjv-github
    token:
      secure: MoK6AtmZzSRk7oBuf5DoTLLQis/UEuctVglJsNkvV7pE27FqwbpumIwQkrnLBqox1h0swzU+johE0uLSrcHMjMSp5DCmOm7kzQWaHAg7PtJ+Z1Gf6TgrrIUaJalG0C+wwY5GAdx11Ic4DZkQb6ch4T9EaxazKCDSWSqULNfjoY4zucPqF2Jr5sLHnhlC8mqxHIH2z0p8PEEyRC7aRe3qkpGnyf7Gp8ZhzHK5X6X/vbw7osxn9fTSYyCCHKTZ/vb4S4bPHODj29QFH90Ark8DzTMwr0MmmpSyI1rWImlJOWlQ8+CQC5830VHg4JRGxy6jdFOlMbmQ5U8HyY6S1mwDDTzRI9ShjEputGrt5Yl5tBvK0s/3pVNE4kI18khz+mlsP/kLW+Z5kM8lCiXxhKunHPqjlF126AtWTvS4btg7vSyOqm4zzPWu/bMuq4dti4GqnfWfzczgxlnUoxlU90hLR3ttXVdlZ7XKXh71L5KWQVu1UzhcXymlDKe+xWIIvzWuCNsxMoJjjKDEJ5R+aO176A3OdOnlQ6k4QcPvFz8QXc+qdgiiTPvXijao69vxlEi+XyVlm2ordO0OwpSwi/f/gKqC4QmVSKX5XZvcsYrJg9qICIUHT8r75NkMpUelqqdMbKabFPk+gUjp9nISTwBROXQHgKL0wQFKGCd26OrOk8w=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: heroku  
  api_key:
    secure: Rny+EyCo066JRynOP3k4bEpvS1BRHPs6WKfYQpLRAWYPc9jdIkjfUP7rno6qPuUk49nkiNNJNBJdiOP7o6D57efI22l/YNUlX0KoSe2QcJ/P4/RHFTCFO/nb2vT3q+aeJ9+/wAKG23/Y9+++d3yaqw7CPzQ2zBSTQwljtH6om7oyfyTZznUZ0shzV180Ze6ddnkpDpT5DWs8xyLswV2TCT8zDo1UmqOwFkWWUt0leEE+AJii6A7txBpdZXLtlFNTah2nr4lCgNUBUkVPXn69P0fwZP+822IMGLXyqI+5MzYwp0qh7K2SO+p938K2aGoCAxcoAdHn7xxj6KkxZGH7h0p3E533VFPkMATJqmTaLeoYSnAjOLT1HEHER7A8ukZgnljnWyV3ACpm88mSakxNEAwL5q4IaWXIsemN7r2F5YLpys3MaqiHYftZWL1lsguOJGVwh0AgyHKbvQq9qxNz/8vkZ94tHNd/zR7xbUpNyN16esa/INwL1of5vfzB9B56cEnJ3GLdCcgEPWxzOThnp7cDVvPjkzM5fM8OaPezsjs825bhZ84htpcJjmaGR0xx/uK08rEo2+0ON3xDHB5f7OA74Mhn1g3t5/nTf6Zh4vn26N1z3/I+YvgQdFD+/Pi0lHrbhKy0PqdkAfo5CTgrPEcfDsZK4L0iYX+9YnzK2Qk=
  app: johnymjv-testci2
