## YAML Template.
language: java
addons:
  sonarcloud:
    organization: "johnymjv-github"
    token:
      secure: yykw2OAegdSe5I0Trg/1Nx+EwRul9C1vbaMmlRxFS15SYiPpLejzoWPUfAtYpa7wKFgfxb40rWMwwjaHw01mPaUY54UfRc+aUIdfbNSgo5h70T1iekjQOYttUGwWMJ9ZP2J5x/frpyvTsU0q03ipXOEjJ5svBjCVw/VTYcTG5pspthR+egqsb+4et8oowvd20Qn6DOCwHRUHczUjDWkmGahx5pDsyf7IRoLb+Bnrj33ag1MHwEW5CgeLoCmKaK9quZAgcy1wMpAdYO7JqcjjYXvPQVB/ZcUQV15+wFYCevWKGUn2MQlyVgRXgO7tg7KtIg6V2eba1ANqSjEuq1lp05gkTqnUHeSKR3J/L7tyADPskRkoiY2oF5gCSDGRHErMEEUZ5SLSnmJVFPfAqF4qLHdPu3aFIwpwwusXgIIygj5AEnhz9v/a+ObO1t7oNfw9IwKEBoqD5u/c7o/iEdgD+La7r2WwzS+WuIw4gPC+V1QKbVmCFsEO3ffbfUGuAjFPHHVzfXf8GzQdBtWmmajrnEUM7iOzI8fV43iTQzFj7SqyNLhdCGNUkvvDz5ivC4wypCYmOAZmm+br9rWJkgOkO52x38ic50UzdMak07aYG0AMHr1cbjv56esTgQ8Be3Y13LtiMrX2Un7rayBrSo1zi6I2vHofjiTpCIr80Kn7TbU=
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
